### ISSUE TITLE
USB connection fails

### ISSUE THREAD

**Issue by dapug** [ms-iot/windows-remote-arduino-samples#10]
This app simply refuses to connect to Arduino Uno using USB.

error:  
```
UsbSerial::connectToDeviceAsync failed with a Platform::Exception type. (message: Catastrophic failure

Unable to initialize the device. Did you forget your USB device capabilities in the manifest? SerialDevice::FromIdAsync returned null.)
```

Furthermore, the related official app in the Windows Store has the same issue (see reviews here)
https://www.microsoft.com/en-us/store/p/windows-remote-arduino-experience/9nblggh2041m

I'm really quite surprised to see this issue not addressed.  It's been how many moons?  Is Arduino really a thing for the Core IoT movement, or is it a neat short term idea that was abandoned?  What is the magic secret to getting this working?

My setup:
- Windows 10 14393
- VS 2017 RTM
- Arduino Uno with StandardFirmata loaded at default 57600 baud

My Arduino device shows up in the app, so clearly serial is working (app can see USB devices).  I can see the name/id come through fine when I select one to connect ([ConnectionPage.xaml.cs line 217](https://github.com/ms-iot/windows-remote-arduino-samples/blob/develop/win10/RemoteBlinky/RemoteBlinky/ConnectionPage.xaml.cs#L217)).   But... 'OnDeviceConnectionFailed' is called every time with the error above.

Why???

**Comment by bfjelds** [comment]
Are you running the app on your desktop or on an Iot device?  If on an Iot device, which one ... if on desktop, what version are you using (home, enterprise, etc)?

**Comment by IoTGirl** [comment]
Hi @dapug ,

Arduino Remote Wiring is literally what you make of it.  It is a stand alone GITHUB sample that you can compile but you do need to follow the documented steps at https://github.com/ms-iot/remote-wiring

Specifically the error message is telling you that you likely missed this step:

_Verify your package.appxmanifest file in your Windows solution contains the necessary device capabilities._

The App in the store is compiled for one Arduino platform and clearly states :

> "Make sure StandardFirmata is uploaded to the board you are connecting to, and make note of the baud rate you are using if connecting via USB or Bluetooth.".

Devices that meet the requirements will connect  as you see that other users have posted that their devices do connect with the same version of the software.

Sincerely,

IoTGirl

**Comment by edgardmi** [comment]
Resolution: http://robeich.azurewebsites.net/2015/12/31/c-entwicklung-arduinogenuino/

**Comment by IoTGirl** [comment]
Thanks for the follow up @edgardmi !
